name: Install npm dependencies with cache
description: Install npm dependencies, using cache if available
inputs:
  cache:
    description: Wheather or not to cache
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.cache == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || ${{ inputs.cache == 'false' }}
      run: npm ci
      shell: bash
